[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.build]
cmds = ['npm ci', 'npm run build', 'composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080'